apps/show_users/urls.py
from django.contrib import admin
from django.urls import path, include
from show_users import views
from django.views.generic.base import TemplateView

from show_users.settings import base as settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("oidc/", include("mozilla_django_oidc.urls")),
    # path('', views.home, name='home')
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
]

if settings.DEBUG:
    from django.conf.urls.static import static

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/vei_platform/api/urls.py
from django.urls import path

from .electricity_prices import ElectricityBillingZoneListAPIView
from .electricity_prices import ElectricityPricePlanListAPIView
from .electricity_prices import ElectricityPricesAPIView
from .electricity_prices import ElectricityProductionAPIView
from .electricity_prices import ElectricityFactoryAPIView
from .electricity_prices import ElectricityFactoryScheduleAPIView
from .electricity_prices import ElectricityPricePlanSummaryAPIView

urlpatterns = [
    path("zones", ElectricityBillingZoneListAPIView.as_view(), name="billing_zones"),
    path("plans", ElectricityPricePlanListAPIView.as_view(), name="plans_api"),
    path(
        "plan/summary",
        ElectricityPricePlanSummaryAPIView.as_view(),
        name="plan_summary_api",
    ),
    path("prices", ElectricityPricesAPIView.as_view(), name="prices"),
    path("production", ElectricityProductionAPIView.as_view(), name="production_api"),
    path("factories", ElectricityFactoryAPIView.as_view(), name="my_factories_api"),
    path("schedule", ElectricityFactoryScheduleAPIView.as_view(), name="schedule_api"),
]

apps/vei_platform/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

from .views.factory import (
    FactoriesList,
    FactoryDetail,
    FactoriesOfUserList,
    FactoryCreate,
    FactoryEdit,
    FactoryProduction,
    FactoryProductionChart,
    FactoryScheduleView,
)

from .views.dashboard import Dashboard
from .views.home import Home
from .views.profile import Profile, MyProfileUpdate
from .views.legal_entity import (
    view_entity_detail,
    view_my_entity_detail,
    view_entity_platform,
)
from .views.electricity_prices import ElectricityPriceChart, ElectricityPlanView
from .views.scriping_tools import view_scriping_tools
from .views.team import Team
from django.contrib.sitemaps.views import sitemap
from .sitemaps import ElectricityFactorySitemap


sitemaps = {
    "factories": ElectricityFactorySitemap,
}

urlpatterns = [
    path("admin/", admin.site.urls),
    path("i18n/", include("django.conf.urls.i18n")),
    path("oidc/", include("mozilla_django_oidc.urls")),
    path("ht/", include("health_check.urls")),
    path("api/v1/", include("vei_platform.api.urls")),
    path(
        "robots.txt",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
    ),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path("", Home.as_view(), name="home"),
    path("team", Team.as_view(), name="team"),
    path("dashboard", Dashboard.as_view(), name="dashboard"),
    path("profile", MyProfileUpdate.as_view(), name="my_profile"),
    path("profile/<int:pk>", Profile.as_view(), name="user_profile"),
    path("factory/all", FactoriesList.as_view(), name="factories_all"),
    path("factory/", FactoriesOfUserList.as_view(), name="my_factories"),
    path("factory/add", FactoryCreate.as_view(), name="factory_create"),
    path("factory/<int:pk>", FactoryDetail.as_view(), name="view_factory"),
    path("factory/<int:pk>/edit", FactoryEdit.as_view(), name="factory_edit"),
    path(
        "factory/<int:pk>/production",
        FactoryProduction.as_view(),
        name="factory_production",
    ),
    path(
        "factory/production/chart",
        FactoryProductionChart.as_view(),
        name="factory_production_chart",
    ),
    path(
        "factory/<int:pk>/schedule",
        FactoryScheduleView.as_view(),
        name="factory_schedule",
    ),
    path("price/chart", ElectricityPriceChart.as_view(), name="energy_price_chart"),
    path("price", ElectricityPlanView.as_view(), name="view_electricity_plan"),
    path("entity/<int:pk>", view_entity_detail, name="entity"),
    path("entity/my_entity", view_my_entity_detail, name="my_entity"),
    path("entity/platform", view_entity_platform, name="platform_legal"),
    path("tools/scriping", view_scriping_tools, name="scriping_tools"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/vei_platform/models/factory.py
from django.db import models
from .legal import LegalEntity, add_legal_entity
from .profile import get_user_profile
from django.db.models.signals import post_save
from django.conf import settings
from decimal import Decimal
from django.dispatch import receiver

from .restricted_file_field import RestrictedFileField
from django.utils.translation import gettext_lazy as _
from django.urls import reverse
from .timezone_choises import TIMEZONE_CHOICES
from djmoney.models.fields import CurrencyField

import os
from django.db import models

from . import TimeStampMixin
from . import unique_slug_generator
from .electricity_price import ElectricityPricePlan, ElectricityPrice
import pytz


def user_image_upload_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return "images/user_{0}/{1}".format(str(instance.manager), filename)


def factory_component_file_upload_directory_path(instance, filename):
    return "documents/factory_{0}/{1}".format(instance.factory.pk, filename)


class ElectricityFactory(TimeStampMixin):
    name = models.CharField(max_length=128)
    slug = models.SlugField(unique=True, null=True, blank=False)  # Ensure unique slugs

    # Factory type
    PHOTOVOLTAIC = "FEV"
    WIND_TURBINE = "WIN"
    HYDROPOWER = "HYD"
    BIOMASS = "BIO"
    REN_GAS = "RGS"

    FACTORY_TYPE_CHOISES = (
        (PHOTOVOLTAIC, _("Photovoltaic")),
        (WIND_TURBINE, _("Wind turbine")),
        (HYDROPOWER, _("Hydropower")),
        (BIOMASS, _("Biomass")),
        (REN_GAS, _("Renewable gas")),
    )

    factory_type = models.CharField(
        max_length=3,
        choices=FACTORY_TYPE_CHOISES,
        default=PHOTOVOLTAIC,
    )

    # User that manages the data shown on the platform
    manager = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        blank=True,
        default=None,
        on_delete=models.DO_NOTHING,
    )

    # info
    location = models.CharField(max_length=100, default=_("Bulgaria"))
    opened = models.DateField(null=True)
    capacity_in_mw = models.DecimalField(default=0, decimal_places=3, max_digits=9)
    image = models.ImageField(
        upload_to=user_image_upload_directory_path, default=None, null=True, blank=True
    )

    # primary owner
    primary_owner = models.ForeignKey(
        LegalEntity, null=True, blank=True, default=None, on_delete=models.SET_NULL
    )

    tax_id = models.CharField(
        max_length=128,
        null=True,
        blank=True,
        default=None,
    )
    owner_name = models.CharField(max_length=128, default="Unknown")

    factory_code = models.CharField(
        max_length=128,
        null=True,
        blank=True,
        default=None,
    )

    email = models.EmailField(null=True, blank=True, default=None)
    phone = models.CharField(
        max_length=128,
        null=True,
        blank=True,
        default=None,
    )

    plan = models.ForeignKey(
        ElectricityPricePlan, null=True, blank=True, on_delete=models.SET_NULL
    )
    timezone = models.CharField(
        verbose_name="Timezone",
        max_length=50,
        default="UTC",
        choices=TIMEZONE_CHOICES,
    )
    currency = CurrencyField(default="EUR")

    def __str__(self):
        return self.name

    def is_working(self):
        return self.status == self.WORKING

    def is_stopped(self):
        return self.status == self.STOPED

    def get_image_url(self):
        if self.image and hasattr(self.image, "url"):
            return self.image.url
        if self.factory_type == self.PHOTOVOLTAIC:
            return "/static/img/password_img.jpg"
        if self.factory_type == self.WIND_TURBINE:
            return "/static/img/wind-turbine.jpg"
        if self.factory_type == self.HYDROPOWER:
            return "/static/img/wickramanayaka.jpg"
        print("type = " + self.factory_type + "\n")
        return None

    def get_capacity_in_kw(self):
        return self.capacity_in_mw * Decimal(1000)

    def get_absolute_url(self):
        return reverse("view_factory", kwargs={"pk": self.pk})

    def get_manager_profile(self):
        if self.manager:
            return get_user_profile(self.manager)
        else:
            return None

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = unique_slug_generator(self)  # Handle Unicode characters
        super().save(*args, **kwargs)

    def get_requested_timezone(self) -> str:
        requested_timezone = self.timezone
        if requested_timezone is None:
            requested_timezone = "UTC"
        return requested_timezone

    def get_pytz_timezone(self) -> pytz.timezone:
        requested_timezone = self.timezone
        if requested_timezone is None:
            requested_timezone = "UTC"
        tz = pytz.timezone(requested_timezone)
        return tz

    def get_last_prices(self, num_days):
        if self.plan is None:
            return []
        prices = ElectricityPrice.objects.filter(plan=self.plan).order_by(
            "-start_interval"
        )[: num_days * 24]
        return prices[::-1]


def docfile_content_types():
    return "application/pdf"


class ElectricityFactoryComponents(models.Model):
    # Factory type
    PHOTO_PANEL = "PAN"
    INVERTOR = "INV"
    CONNECTOR = "CON"
    OTHER = "OTH"

    COMPONENT_TYPE_CHOISES = (
        (PHOTO_PANEL, _("Photovoltaic Panel")),
        (INVERTOR, _("Invertor")),
        (CONNECTOR, _("Connector")),
        (OTHER, _("Other")),
    )

    name = models.CharField(max_length=128)
    component_type = models.CharField(
        max_length=3,
        choices=COMPONENT_TYPE_CHOISES,
        default=OTHER,
    )
    factory = models.ForeignKey(
        ElectricityFactory,
        null=True,
        blank=True,
        default=None,
        on_delete=models.DO_NOTHING,
    )
    power_in_kw = models.DecimalField(
        null=True, blank=True, default=None, decimal_places=3, max_digits=9
    )
    count = models.IntegerField(default=1)
    docfile = RestrictedFileField(
        upload_to=factory_component_file_upload_directory_path,
        content_types=docfile_content_types(),  # ['application/pdf',],
        max_upload_size=5242880,  # 5 MB
        default=None,
        null=True,
        blank=True,
    )
    description = models.TextField(null=True, blank=True, default=None)

    def __str__(self) -> str:
        return "%s %s kW x %d" % (self.name, self.power_in_kw, self.count)


def _delete_file(path):
    """Deletes file from filesystem."""
    if os.path.isfile(path):
        # print("cleaning " + path)
        try:
            os.remove(path)
        except FileNotFoundError:
            pass


@receiver(models.signals.post_delete, sender=ElectricityFactoryComponents)
def delete_file(sender, instance, *args, **kwargs):
    """Deletes image files on `post_delete`"""
    if instance.docfile:
        _delete_file(instance.docfile.path)


@receiver(models.signals.pre_save, sender=ElectricityFactoryComponents)
def auto_delete_file_on_change(sender, instance, update_fields, **kwargs):
    """
    Deletes old file from filesystem
    when corresponding `ElectricityFactoryComponents` object is updated
    with new file.
    """
    # print(update_fields)
    if not instance.pk:
        return False

    try:
        old_instance = ElectricityFactoryComponents.objects.get(pk=instance.pk)
        old_file = old_instance.docfile
        should_delete = instance.docfile != old_instance.docfile
        if should_delete and old_file:
            _delete_file(old_file.path)
    except ElectricityFactoryComponents.DoesNotExist:
        return False

apps/vei_platform/models/timezone_choises.py
import pytz

TIMEZONE_CHOICES = []
for tz in pytz.all_timezones:
    TIMEZONE_CHOICES.append((tz, tz))
TIMEZONE_CHOICES = tuple(TIMEZONE_CHOICES)

apps/vei_platform/views/api.py
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticatedOrReadOnly

from vei_platform.models.electricity_price import ElectricityPrice, ElectricityPricePlan

# This tutorial basically covers all REST + token auth
# https://learndjango.com/tutorials/official-django-rest-framework-tutorial-beginners
class HelloView(APIView):
    permission_classes = (IsAuthenticatedOrReadOnly,)
    def get(self, request):
        print(request.headers)
        content = {'message': 'Hello, World!'}
        return Response(content)
    
    def post(self, request):
        #print(request.data)
        #print(request.data.keys())
        if request.data:
            content = {'message': 'Hello, ' + str(request.user) + " Your data is = " + str(request.data)}
            print(request.data)
        else:
            content = {'message': 'Invalid data!!!'}
        return Response(content)

apps/vei_platform/views/dashboard.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

from . import common_context
from vei_platform.models.legal import find_legal_entity
from vei_platform.models.profile import get_user_profile
from vei_platform.models.factory import ElectricityFactory
from django.utils.translation import gettext as _

from django.views import View


class Dashboard(View):
    def get(self, request, *args, **kwargs):
        context = common_context(request)
        if request.user and request.user.is_authenticated:
            self.add_my_legal_entity(request, context)
            return render(request, "dashboard.html", context)
        return redirect("home")

    def add_my_legal_entity(self, request, context):
        if request.user and request.user.is_authenticated:
            context["my_legal_entity"] = find_legal_entity(user=request.user)

apps/vei_platform/views/home.py
from . import common_context

from django.shortcuts import render
from django.views import View


class Home(View):
    def get(self, request, *args, **kwargs):
        context = common_context(request)
        return render(request, "home.html", context)

apps/vei_platform/views/scriping_tools.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from . import common_context
from vei_platform.forms import FactoryScriperForm
from vei_platform.models.profile import get_user_profile
from vei_platform.models.legal import LegalEntity, find_legal_entity, add_legal_entity
from django.contrib import messages
from django_q.tasks import async_task

from django.utils.translation import gettext as _


@login_required(login_url="/oidc/authenticate/")
def view_scriping_tools(request):
    context = common_context(request)
    scripe_form = FactoryScriperForm(request.POST)
    if request.method == "POST":
        # TODO, only admin should be able to trigger this
        if "scripe_page" in request.POST and scripe_form.is_valid():

            try:
                page_number = int(scripe_form.cleaned_data.get("page_number"))
                limit = 1
                async_task(
                    "vei_platform.tasks.scripe_factories_list", page_number, limit
                )
                messages.success(
                    request, "Form is valid with number = %d" % page_number
                )
            except ValueError:
                messages.error(
                    request, "Form cleaned data = " + str(scripe_form.cleaned_data)
                )

        if "scripe_all" in request.POST:
            page_number = 1
            limit = 10000
            async_task("vei_platform.tasks.scripe_factories_list", page_number, limit)
            messages.success(request, "Scriping all pages!")

        if "scripe_tax_id" in request.POST and scripe_form.is_valid():
            tax_id = scripe_form.cleaned_data.get("tax_id")
            task_name = "LegalEntity-for-%s" % tax_id
            async_task(
                "vei_platform.tasks.scripe_legal_entity",
                tax_id=tax_id,
                hook=add_legal_entity,
            )
            messages.success(request, "Spawned %s" % task_name)

    context["scripe_form"] = scripe_form
    return render(request, "scriping_tools.html", context)

apps/vei_platform/templates/snippets/energy_price_chart.html
<script>
    $(function () {
        var $my_chart = $("#energy-price-chart");
        $.ajax({
            url: $my_chart.data("url"),
            success: function (data) {
                var ctx = $my_chart[0].getContext("2d");
                new Chart(ctx, {
                    type: 'line',
                    data: {
                        labels: data.labels,
                        datasets: [{
                            label: data.plan_name,
                            data: data.data,
                            fill: false,
                            stepped: true,
                            step: 'after',
                            //step: 'middle',
                            tension: 0.1,
                            borderColor: 'rgb(0, 99, 132)',
                            backgroundColor: 'rgba(255, 99, 132, 0.2)',
                        }],
                    },
                    options: {
                        responsive: true,
                        legend: {
                            position: 'bottom',
                        },
                        title: {
                            display: true,
                            text: data.title
                        },
                        layout: {
                            padding: {
                                left: 10,
                                right: 25,
                                top: 25,
                                bottom: 0
                            }
                        },
                        scales: {
                            x: {
                                type: 'time',
                                time: {
                                    unit: 'hour'
                                },
                                min: data.x_min,
                                max: data.x_max,
                                display: true,
                                title: {
                                    display: true,
                                    text: data.x_scale,
                                },
                                ticks: {
                                    autoSkip: false,
                                    maxRotation: 0,
                                    major: {
                                        enabled: true
                                    },
                                    // color: function(context) {
                                    //   return context.tick && context.tick.major ? '#FF0000' : 'rgba(0,0,0,0.1)';
                                    // },
                                    font: function (context) {
                                        if (context.tick && context.tick.major) {
                                            return {
                                                weight: 'bold',
                                            };
                                        }
                                    }
                                }
                            },
                            y: {
                                display: true,
                                title: {
                                    display: true,
                                    text: data.y_scale,
                                },
                                //min: 0,
                                //max: 500
                            }
                        },
                    }
                });

            }
        });

    });

</script>

apps/vei_platform/templates/snippets/factories_list.html
{% for factory in page_obj %}
{% include "snippets/factory_card.html"%}
{% endfor%}

apps/vei_platform/templates/snippets/factory_card_show_invest_form.html
{% load crispy_forms_tags %}

{% include "snippets/factory_card_progress.html" %}
<hr>
{% crispy invest_form %}

apps/vei_platform/templates/snippets/factory_components.html
{% if components|length > 0 %}
{% load vei_platform_utils %}
{% load i18n %}

<div class="row justify-content-center">
    <div class="col-md-12 col-xl-10">
        <h2 class="text-center">{% trans "Details for this project" %}</h2>
        <table class="table align-middle mb-0 bg-white">
            <thead class="bg-light">
                <th>{% trans "Type" %}</th>
                <th>{% trans "Name" %}</th>
                <th>{% trans "Power [kw]" %}</th>
                <th>{% trans "Count" %}</th>
                <th>{% trans "Document" %}</th>
            </thead>
            <tbody>
                {% for comp in components %}
                <tr class="bg-light">
                    <td>{{comp.get_component_type_display }}</td>
                    <td>
                        {% if comp.description %}

                        <a data-toggle="collapse" href="#collapseExample_{{ forloop.counter }}" aria-expanded="false"
                            aria-controls="collapseExample_{{ forloop.counter }}">
                            {{comp.name}}
                        </a>
                        {% else %}
                        {{comp.name}}
                        {% endif %}
                    </td>
                    <td>{{comp.power_in_kw}}</td>
                    <td>{{comp.count}}</td>
                    <td>{% if comp.docfile %}
                        <a href="/media/{{comp.docfile}}">
                            <i class="fa fa-file"></i>
                            {% comment %}
                            {{comp.docfile.name|basename}}
                            {% endcomment %}
                        </a>
                        {% endif %}
                    </td>
                </tr>

                {% if comp.description %}

                <tr>
                    <td colspan="5" class="text-justify">
                        <div class="collapse" id="collapseExample_{{ forloop.counter }}">
                            {{ comp.description | linebreaks }}
                        </div>
                    </td>
                </tr>
                {% endif %}

                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endif %}

apps/vei_platform/templates/snippets/formset.html
{% load crispy_forms_tags %}


{% comment %}

{{ formset.management_form }}

{% if helper %}
{% crispy formset helper %}
{% else %}
{{ formset|crispy }}
{% endif %}

{% endcomment %}



<table class="table table-striped table-bordered ">
    {{ formset.management_form }}
    {% for form in formset.forms %}
    {% if forloop.first %}
    <thead>
        <tr>
            {% comment %}
            {% for field in form.visible_fields %}
            <th>{{ field.label|capfirst }}</th>
            {% endfor %}
            {% endcomment %}
        </tr>
    </thead>
    <tbody>
        {% endif %}


        <tr class="{% cycle row1 row2 %} formset_row">
            <td>
                {% for field in form.visible_fields %}

                {# Include the hidden fields in the form #}
                {% if forloop.first %}
                {% for hidden in form.hidden_fields %}
                {{ hidden }}
                {% endfor %}
                {% endif %}
                {{ field | as_crispy_field }}
                {% if field.name == 'docfile' or field.name == 'description' %}
            </td>
            <td>
                {% endif %}

                {% endfor %}
            </td>
        </tr>
        {% if forloop.last %}
    </tbody>
    {% endif %}
    {% endfor %}
</table>

<script type="text/javascript">
    $(function () {
        $('.formset_row').formset({
            addText: '<i class="fas fa-plus-circle"></i>',          // Text for the add link
            deleteText: '<i class="fas fa-trash"></i>',            // Text for the delete link
        });
    })
</script>

apps/vei_platform/templates/snippets/header_messages.html
<div class="dropdown dib">
    <div class="header-icon" data-toggle="dropdown">
        <i class="ti-email"></i>
        <div class="drop-down dropdown-menu dropdown-menu-right">
            <div class="dropdown-content-heading">
                <span class="text-left">2 New Messages</span>
                <a href="email.html">
                    <i class="ti-pencil-alt pull-right"></i>
                </a>
            </div>
            <div class="dropdown-content-body">
                <ul>
                    <li class="notification-unread">
                        <a href="#">
                            <img class="pull-left m-r-10 avatar-img" src="images/avatar/1.jpg" alt="" />
                            <div class="notification-content">
                                <small class="notification-timestamp pull-right">02:34 PM</small>
                                <div class="notification-heading">Michael Qin</div>
                                <div class="notification-text">Hi Teddy, Just wanted to let you ...</div>
                            </div>
                        </a>
                    </li>
                    <li class="notification-unread">
                        <a href="#">
                            <img class="pull-left m-r-10 avatar-img" src="images/avatar/2.jpg" alt="" />
                            <div class="notification-content">
                                <small class="notification-timestamp pull-right">02:34 PM</small>
                                <div class="notification-heading">Mr. John</div>
                                <div class="notification-text">Hi Teddy, Just wanted to let you ...</div>
                            </div>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <img class="pull-left m-r-10 avatar-img" src="images/avatar/3.jpg" alt="" />
                            <div class="notification-content">
                                <small class="notification-timestamp pull-right">02:34 PM</small>
                                <div class="notification-heading">Michael Qin</div>
                                <div class="notification-text">Hi Teddy, Just wanted to let you ...</div>
                            </div>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <img class="pull-left m-r-10 avatar-img" src="images/avatar/2.jpg" alt="" />
                            <div class="notification-content">
                                <small class="notification-timestamp pull-right">02:34 PM</small>
                                <div class="notification-heading">Mr. John</div>
                                <div class="notification-text">Hi Teddy, Just wanted to let you ...</div>
                            </div>
                        </a>
                    </li>
                    <li class="text-center">
                        <a href="#" class="more-link">See All</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

apps/vei_platform/templates/snippets/header_notifications.html
<div class="dropdown dib">
    <div class="header-icon" data-toggle="dropdown">
        <i class="ti-bell"></i>
        <div class="drop-down dropdown-menu dropdown-menu-right">
            <div class="dropdown-content-heading">
                <span class="text-left">Recent Notifications</span>
            </div>
            <div class="dropdown-content-body">
                <ul>
                    <li>
                        <a href="#">
                            <img class="pull-left m-r-10 avatar-img" src="images/avatar/3.jpg" alt="" />
                            <div class="notification-content">
                                <small class="notification-timestamp pull-right">02:34 PM</small>
                                <div class="notification-heading">Mr. John</div>
                                <div class="notification-text">5 members joined today </div>
                            </div>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <img class="pull-left m-r-10 avatar-img" src="images/avatar/3.jpg" alt="" />
                            <div class="notification-content">
                                <small class="notification-timestamp pull-right">02:34 PM</small>
                                <div class="notification-heading">Mariam</div>
                                <div class="notification-text">likes a photo of you</div>
                            </div>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <img class="pull-left m-r-10 avatar-img" src="images/avatar/3.jpg" alt="" />
                            <div class="notification-content">
                                <small class="notification-timestamp pull-right">02:34 PM</small>
                                <div class="notification-heading">Tasnim</div>
                                <div class="notification-text">Hi Teddy, Just wanted to let you ...</div>
                            </div>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <img class="pull-left m-r-10 avatar-img" src="images/avatar/3.jpg" alt="" />
                            <div class="notification-content">
                                <small class="notification-timestamp pull-right">02:34 PM</small>
                                <div class="notification-heading">Mr. John</div>
                                <div class="notification-text">Hi Teddy, Just wanted to let you ...</div>
                            </div>
                        </a>
                    </li>
                    <li class="text-center">
                        <a href="#" class="more-link">See All</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>